from romanos.gramaticas.quatroDigitosRomanos import QuatroDigitosRomanos
from romanos.gramaticas.tresDigitosRomanos import TresDigitosRomanos
from romanos.gramaticas.doisDigitosRomanos import DoisDigitosRomanos
from romanos.gramaticas.umDigitoRomano import UmDigitoRomano
